version: '3.8'
services:
  web:
    build:
      context: ./pyapimysql
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - JWT_SECRET_KEY=your_secret_key
    volumes:
      - ./pyapimysql/src:/app
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: api_flask
    ports:
      - "3306:3306"