version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: apiflask-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: api_flask
      # Eliminamos MYSQL_USER y MYSQL_PASSWORD ya que usaremos root
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  web:
    build: .
    container_name: apiflask-web
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: api_flask

networks:
  mynetwork:
    driver: bridge